#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#############################
#   Entry point functuons   #
#############################

CWMP_LAN_IF="br-lan"

prefix_list="$prefix_list $DMROOT.LANDevice."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_LANDevice"

entry_execute_method_root_LANDevice() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.LANDevice."*)
		common_execute_method_obj "$DMROOT.LANDevice." "0"
		common_execute_method_obj "$DMROOT.LANDevice.1." "0" "" "" "lan_device_browse_instances_LAN_Ethernet_Interface_Number_Of_Entries $1"

		common_execute_method_obj "$DMROOT.LANDevice.1.LANHost." "0" 
		common_execute_method_param "$DMROOT.LANDevice.1.LANHost.LocalAddresses" "0" "" "" "" 

		common_execute_method_obj "$DMROOT.LANDevice.1.WLANConfiguration." "1" "lan_device_add_wlan_iface" "" "lan_device_browse_instances_wlan_iface $1"
		common_execute_method_obj "$DMROOT.LANDevice.1.Hosts." "0"
		common_execute_method_obj "$DMROOT.LANDevice.1.Hosts.LANInterfaces." "0"
		common_execute_method_param "$DMROOT.LANDevice.1.Hosts.LANInterfaces.LANEthernetInterfaceNumberOfEntries" "0" "get_lan_device_lan_ethernet_number_of_entries" "" "" 
		common_execute_method_param "$DMROOT.LANDevice.1.Hosts.LANInterfaces.LANWLANConfigurationNumberOfEntries" "0" "get_lan_device_wlan_number_of_entries" "" "" 

		common_execute_method_obj "$DMROOT.LANDevice.1.Hosts.Host." "0" "" "" "lan_device_browse_instances_Hosts_Host $1"
		common_execute_method_obj "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig." "0" "" "" "lan_device_browse_instances_LAN_Ethernet_Interface_Config $1"
		common_execute_method_obj "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1." "0" "" "" "lan_device_browse_instances_LAN_Ethernet_Interface_Config_Stats $1"
		common_execute_method_obj "$DMROOT.LANDevice.1.LANHostConfigManagement." "0" "" "" "lan_device_browse_instances_LAN_Host_Config_Management $1"
		common_execute_method_obj "$DMROOT.LANDevice.1.LANHostConfigManagement.IPInterface." "0" "" "" "lan_device_browse_instances_LAN_Host_Config_Management_Ip_Interface $1"
		return 0
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

sub_entry_landevic_LAN_Ethernet_Interface_Number_Of_Entries() {
	local j="$2"
	local iface="$3"
	case_param "$1" belongto "$DMROOT.LANDevice.1." && {
		common_execute_method_obj "$DMROOT.LANDevice.1." "0" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceNumberOfEntries" "0" "get_lan_device_lan_ethernet_interface_number_of_entries" "" "" "1"
		common_execute_method_param "$DMROOT.LANDevice.1.LANWLANConfigurationNumberOfEntries" "0" "get_lan_device_lan_wlan_configuration_number_of_entries" "" "" "1"
		return 0
	}
	return $E_INVALID_PARAMETER_NAME;
}


sub_entry_landevice_wlanconfig() {
	local j="$2"
	local iface="$3"
	case_param "$1" belongto "$DMROOT.LANDevice.1.WLANConfiguration.$j." && {
		common_execute_method_obj "$DMROOT.LANDevice.1.WLANConfiguration.$j." "1" "" "lan_device_delete_wlan_iface $iface"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.Enable" "1" "lan_device_get_wlan_enable $iface" "lan_device_set_wlan_enable $iface" "xsd:boolean"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.Status" "0" "lan_device_get_wlan_status" ""
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.PossibleChannels" "0" "lan_device_get_wlan_possiblechannels" ""
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.SSID" "1" "$UCI_GET wireless.$iface.ssid" "lan_device_set_wlan_cfg wireless.$iface.ssid"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.WebAccessEnable" "1" "lan_device_get_wlan_webenable" "lan_device_set_wlan_webenable"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.Channel" "1" "lan_device_get_wlan_channel" "lan_device_set_wlan_channel"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.ChannelsInUse" "0" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.BeaconType" "0" "lan_device_get_wlan_beacontype $iface" "lan_device_set_wlan_beacontype $iface"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.BeaconAdvertisementEnabled" "1" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.Standard" "1" "lan_device_get_wlan_Standard" "lan_device_set_wlan_Standard"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.KeyPassphrase" "1" "lan_device_get_wlan_KeyPassphrase $iface" "lan_device_set_wlan_KeyPassphrase $iface"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.BasicEncryptionModes" "1" "lan_device_get_wlan_basicencrymodes $iface" "lan_device_set_wlan_basicencrymodes $iface"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.BasicAuthenticationMode" "1" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.RadioEnabled" "1" "lan_device_get_wlan_RadioEnabled" "lan_device_set_wlan_RadioEnabled"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.WPAEncryptionModes" "1" "lan_device_get_wlan_WPAEncryptionModes $iface" "lan_device_set_wlan_WPAEncryptionModes $iface"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.X_CT-COM_ChannelWidthandard" "1" "lan_device_get_wlan_channelwh" "lan_device_set_wlan_channelwh"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.X_CT-COM_Powerlevel" "1" "lan_device_get_wlan_powerlevel" "lan_device_set_wlan_powerlevel"
		common_execute_method_param "$DMROOT.LANDevice.1.WLANConfiguration.$j.X_CT-COM_APModuleEnable" "1" "lan_device_get_wlan_apenable" "lan_device_set_wlan_apenable"


		return 0
	}
	return $E_INVALID_PARAMETER_NAME;
}

sub_entry_landevice_Hosts_Host() {
	return 0;
}

sub_entry_landevice_LAN_Ethernet_Interface_Config() {
	local j="$2"
	local iface="$3"
	case_param "$1" belongto "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1." && {
		common_execute_method_obj "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1." "0" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.Enable" "0" "get_lan_device_lan_ethernet_interface_config_enable" "" "" "1"
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.MACAddress" "0" "get_lan_device_lan_ethernet_interface_config_macaddress" "" "" "1"
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.Status" "0" "get_lan_device_lan_ethernet_interface_config_status" "" "" "1"
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.MACAddressControlEnabled" "0" "get_lan_device_lan_ethernet_interface_config_macenabled" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.MaxBitRate" "0" "get_lan_device_lan_ethernet_interface_config_maxbitrate" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.DuplexMode" "0" "" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.X_CT-COM_Mode" "0" "" "" ""


		return 0
	}
	return $E_INVALID_PARAMETER_NAME;
}

sub_entry_landevice_LAN_Ethernet_Interface_Config_Stats() {
	local j="$2"
	local iface="$3"
	case_param "$1" belongto "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.Stats." && {
		common_execute_method_obj "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.Stats." "0" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.Stats.BytesSent" "0" "get_lan_device_lan_ethernet_interface_config_stats_bytessent" "" "" "1"
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.Stats.BytesReceived" "0" "get_lan_device_lan_ethernet_interface_config_stats_bytesreceived" "" "" "1"
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.Stats.PacketsSent" "0" "get_lan_device_lan_ethernet_interface_config_stats_packetssent" "" "" "1"
		common_execute_method_param "$DMROOT.LANDevice.1.LANEthernetInterfaceConfig.1.Stats.PacketsReceived" "0" "get_lan_device_lan_ethernet_interface_config_stats_packetsreceived" "" "" "1"
		return 0
	}
	return $E_INVALID_PARAMETER_NAME;
}

sub_entry_landevice_LAN_Host_Config_Management(){
	local j="$2"
	local iface="$3"
	case_param "$1" belongto "$DMROOT.LANDevice.1.LANHostConfigManagement." && {
		common_execute_method_obj "$DMROOT.LANDevice.1.LANHostConfigManagement." "0" "" ""


		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.MACAddress" "0" "get_lan_device_lan_host_config_management_mac_addr" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.DHCPServerConfigurable" "1" "get_lan_device_lan_host_config_management_dhcp_server_configenable" "set_lan_device_lan_host_config_management_dhcp_server_configenable" "" 		
		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.DHCPServerEnable" "1" "get_lan_device_lan_host_config_management_dhcp_server_enable" "set_lan_device_lan_host_config_management_dhcp_server_enable" "" "1"
		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.DHCPRelay" "0" "get_lan_device_lan_host_config_management_dhcp_relay" "" "" "1"

		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.MinAddress" "1" "get_lan_device_lan_host_config_management_min_address" "set_lan_device_lan_host_config_management_min_address" "" "1"
		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.MaxAddress" "1" "get_lan_device_lan_host_config_management_max_address" "set_lan_device_lan_host_config_management_max_address" "" "1"
		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.ReservedAddresses" "0" "" "" ""
		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.SubnetMask" "1" "get_lan_device_lan_host_config_management_subnet_mask" "set_lan_device_lan_host_config_management_subnet_mask" ""
		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.DNSServers" "1" "get_lan_device_lan_host_config_management_dns_servers" "set_lan_device_lan_host_config_management_dns_servers" ""
		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.DomainName" "1" "get_lan_device_lan_host_config_management_domain_name" "set_lan_device_lan_host_config_management_domain_name" ""



		common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.DHCPLeaseTime" "1" "get_lan_device_lan_host_config_management_dhcp_lease_time" "set_lan_device_lan_host_config_management_dhcp_lease_time" "" "1"
		return 0 
	}
	return $E_INVALID_PARAMETER_NAME;
}

#######################################
#     Data model browse instances     #
#######################################


lan_device_browse_instances_LAN_Ethernet_Interface_Number_Of_Entries(){
	sub_entry_landevic_LAN_Ethernet_Interface_Number_Of_Entries "$1" "1" "1"
	return 0
}

lan_device_browse_instances_wlan_iface() {
	local iface ifaces=`$UCI_SHOW wireless | grep "wireless\.@wifi-iface\[.*\]=wifi-iface" | awk -F'[.=]' '{print $2}'` 
	for iface in $ifaces; do
		local j=`lan_device_update_instance $iface`
		j=$(($j+1))
		sub_entry_landevice_wlanconfig "$1" "$j" "$iface"
	done
	return 0
}

lan_device_browse_instances_LAN_Ethernet_Interface_Config() {
	sub_entry_landevice_LAN_Ethernet_Interface_Config "$1" "1" "1"
	return 0
}

lan_device_browse_instances_Hosts_Host() {
	sub_entry_landevice_Hosts_Host "$1" "1" "1"
	return 0
}

lan_device_browse_instances_LAN_Ethernet_Interface_Config_Stats(){
	sub_entry_landevice_LAN_Ethernet_Interface_Config_Stats "$1" "1" "1"
	return 0
}
 
lan_device_browse_instances_LAN_Host_Config_Management(){
	sub_entry_landevice_LAN_Host_Config_Management "$1" "1" "1"
	return 0
}

sub_entry_landevice_IP_Interface()
{
    local j="$2"
    local iface="$3"
    case_param "$1" belongto "$DMROOT.LANDevice.1.LANHostConfigManagement.IPInterface.$j." && {
	common_execute_method_obj "$DMROOT.LANDevice.1.LANHostConfigManagement.IPInterface.$j." "0" "" ""
    	common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.IPInterface.$j.Enable" "1" "lan_device_get_host_enable $iface" "lan_device_set_host_enable $iface" 
    	common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.IPInterface.$j.IPInterfaceIPAddress" "1" "lan_device_get_host_ip_interface $iface" "lan_device_set_host_ip_interface $iface" 
    	common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.IPInterface.$j.IPInterfaceSubnetMask" "1" "lan_device_get_host_subnet_mask $iface" "lan_device_set_host_subnet_mask $iface" 
    	common_execute_method_param "$DMROOT.LANDevice.1.LANHostConfigManagement.IPInterface.$j.IPInterfaceAddressingType" "1" "lan_device_get_host_addr_type $iface" "" 

    	return 0
    }
    return $E_INVALID_PARAMETER_NAME;
}

lan_device_browse_instances_LAN_Host_Config_Management_Ip_Interface(){
    local j=0
    local lan_iface=""
    local lan_num=0
    while [ $lan_num -le 7 ]
    do
        if [ $lan_num = 0 ];then
          lan_iface="lan"
        else
          lan_iface="lan$lan_num"
        fi
        lan_proto=$(uci get network.$lan_iface.proto) &> /dev/null
        [ -z $lan_proto ] &&
        {
             lan_num=$(($lan_num+1))
             continue
        }||
        {
            j=$(($j+1))
            sub_entry_landevice_IP_Interface "$1" "$j" "$lan_iface"
            lan_num=$(($lan_num+1))
         }
    done
    return 0
}



#######################################
#   Data model parameters functions   #
#######################################


# sub_entry_landevic_LAN_Ethernet_Interface_Number_Of_Entries #
get_lan_device_lan_ethernet_interface_number_of_entries() {
	echo "1"
}

get_lan_device_lan_wlan_configuration_number_of_entries() {
	echo "4"
}

# sub_entry_landevice_LAN_Ethernet_Interface_Config #
get_lan_device_lan_ethernet_interface_config_status() {
local tmp
local val="Disable"

	tmp=`ifconfig $CWMP_LAN_IF |grep $CWMP_LAN_IF |awk '{print $2}'`
	if [ $tmp == "Link" ]; then
		val="NoLink"
	fi
	tmp=`ifconfig $CWMP_LAN_IF |grep "inet addr" |awk '{print $1}'`
	if [ $tmp == "inet" ]; then
		val="Up"
	fi
	echo "$val"
	
return 0	
}

get_lan_device_lan_ethernet_interface_config_macaddress() {
    local val=`uci get network.lan.macaddr`
    if [ -n "$val" ]; then
        echo "$val"
    else
        echo ""
    fi
    
}

# sub_entry_landevice_LAN_Ethernet_Interface_Config_Stats #
get_lan_device_lan_ethernet_interface_config_stats_bytessent(){
	local val=""
	val=`cat /proc/net/dev |grep $CWMP_LAN_IF: | awk '{print $10;}'`
	echo "$val"
	return 0
}

get_lan_device_lan_ethernet_interface_config_stats_bytesreceived(){
	local val=""
	val=`cat /proc/net/dev |grep $CWMP_LAN_IF: | awk '{print $2;}'`
	echo "$val"
	return 0
}

get_lan_device_lan_ethernet_interface_config_stats_packetssent(){
	local val=""
	val=`cat /proc/net/dev |grep $CWMP_LAN_IF: | awk '{print $11;}'`
	echo "$val"
	return 0
}

get_lan_device_lan_ethernet_interface_config_stats_packetsreceived(){
	local val=""
	val=`cat /proc/net/dev |grep $CWMP_LAN_IF: | awk '{print $3;}'`
	echo "$val"
	return 0
}

# sub_entry_landevice_LAN_Host_Config_Management #
get_lan_device_lan_host_config_management_dhcp_server_enable(){
    local cfgval=""
    cfgval=`uci get /etc/config/dhcp.lan.ignore`
    if [ "$cfgval" = "1" ];then
        echo "0"
    else
        echo "1"
    fi
    return 0
}
set_lan_device_lan_host_config_management_dhcp_server_enable(){
    local val=$1
    if [ "$val" = "1" ];then
        uci delete /etc/config/dhcp.lan.ignore
    elif [ "$val" = "0" ];then
        uci set /etc/config/dhcp.lan.ignore="1"        
    else
        return $E_INVALID_PARAMETER_VALUE
    fi
    uci commit /etc/config/dhcp
    /etc/init.d/dnsmasq restart
    /etc/init.d/odhcpd  restart
    return 0
}

get_lan_device_lan_host_config_management_min_address(){
    local lan_ip=`uci get network.lan.ipaddr`
    local lan_pre=`echo ${lan_ip%.*}`
    local start_base=`uci get dhcp.lan.start`
    local min_addr="$lan_pre"".""$start_base"
    echo $min_addr
}
set_lan_device_lan_host_config_management_min_address(){
   local setting_val=$1
   local lan_start=`echo ${setting_val##*.}`
   local lan_ip=`uci get network.lan.ipaddr`
   local lan_pre=`echo ${lan_ip%.*}`
   local min_addr="$lan_pre"".""$lan_start"

   uci set dhcp.lan.start="$lan_start"
   uci set network.lan.ipaddr="$min_addr"
   uci commit dhcp
   uci commit network
   return 0
}

get_lan_device_lan_host_config_management_max_address(){
    local lan_base=`uci get network.lan.ipaddr`
    local lan_pre=`echo ${lan_base%.*}`
    local lan_end=`echo ${lan_base##*.}`
    local limit_addr=`uci get dhcp.lan.limit`
    local max_ip=$(($limit_addr+$lan_end))
    local max_addr="$lan_pre"".""$max_ip"
    echo $max_addr
}
set_lan_device_lan_host_config_management_max_address(){
    local setting_val=$1
    local max_ip=`echo ${setting_val##*.}`
    local lan_base=`uci get network.lan.ipaddr`
    local lan_pre=`echo ${lan_base%.*}`
    local lan_end=`echo ${lan_base##*.}`
    local limit_addr=$(($max_ip-$lan_end))
    uci set dhcp.lan.limit="$limit_addr"
    uci commit network
    return 0
}

get_lan_device_lan_host_config_management_dhcp_lease_time(){
    local val=`uci get dhcp.lan.leasetime`
    if [ -n "$val" ]; then
        echo "$val"
    else
        echo "0"
    fi
}
set_lan_device_lan_host_config_management_dhcp_lease_time(){
    local val=$1
    uci set dhcp.lan.leasetime="$val"
    uci commit dhcp
    return 0
}

# sub_entry_landevice_LAN_Host_Config_Management_Ip_Interface #
get_lan_device_lan_host_config_management_ip_interface_ip_interface_ip_address() {
	local val=""
	#managemidapp -o cusconf -p {"\"StatusGetReq\"":{"\"Oper\"":"\"LAN\""}} -n IP -u uci_tmp.lan_information.lan_ip_address > /tmp/mid_log
	val=`/usr/bin/uci get /etc/config/lte-gw.local_param.local_ip_addr`
	echo "$val"
	return 0	
}
set_lan_device_lan_host_config_management_ip_interface_ip_interface_ip_address() {
	local val=$1
	#managemidapp -o cusconf -p {"\"ConfigSetReq\"":{"\"Oper\"":"\"LAN\"","\"LAN\"":{"\"IP\"":"\"$val\"","\"SubMask\"":"\"255.255.255.0\""}}} > /tmp/mid_log
	echo {"\"ConfigSetReq\"":{"\"Oper\"":"\"LAN\"","\"LAN\"":{"\"IP\"":"\"$val\"","\"SubMask\"":"\"255.255.255.0\""}}} | socat stdio /tmp/cusconf1
	/usr/bin/uci get /etc/config/lte-gw.local_param.local_ip_addr="$val"
}

get_lan_device_lan_host_config_management_ip_interface_ip_interface_subnet_mask() {
	local val=""
	#managemidapp -o cusconf -p {"\"StatusGetReq\"":{"\"Oper\"":"\"LAN\""}} -n SubMask -u uci_tmp.lan_information.lan_subnet_mask > /tmp/mid_log
	val=`/usr/bin/uci get /etc/config/lte-gw.local_param.local_ip_mask`
#	val=`$UCI_GET /tmp/network_status.lan_information.lan_subnet_mask`
	echo "$val"
	return 0	
}

get_lan_device_lan_host_config_management_ip_interface_ip_interface_addressing_type() {
	local val
	local tmp=""
	#managemidapp -o cusconf -p {"\"StatusGetReq\"":{"\"Oper\"":"\"LAN\""}} -n DHCPType -u uci_tmp.lan_information.dhcp_type > /tmp/mid_log
	tmp=`/usr/bin/uci get /etc/config/lte-gw.dhcp_srv.dhcp_enable`
	if [ "$tmp" = "enable" ]; then
		val="DHCP"
	else
		val="Static"	
	fi
	echo "$val"
return 0
}


lan_device_get_wlan_enable() {
    local iface=$1
    local disabled=$(uci get wireless.$iface.disabled) &> /dev/null
    if [ "$disabled" == "1" ]; then
    {    
        echo "0"
    }
    else
        echo "1"
    fi
}

lan_device_set_wlan_enable() {
    local iface=$1
    local val=$2
    if [ "$val" == "1" ]; then
    {    
        uci delete wireless.$iface.disabled
        uci commit wireless    
    }
    elif [ "$val" == "0" ]; then
    {
        uci set wireless.$iface.disabled="1"
        uci commit wireless    
    }
    else
	return $E_INVALID_PARAMETER_VALUE;
    fi
    /etc/init.d/network restart &> /dev/null
    return 0
}

lan_device_set_wlan_cfg() {
	local cfg="$1"
	local val="$2"
	$UCI_SET $cfg="$val"
	return 0
}

lan_device_get_wlan_max_instance() {
	local max=`$UCI_SHOW wireless | grep "wireless\.@wifi-iface\[[0-9]\+\].instance=" | cut -d'=' -f2 | sed 's/[^0-9]*//g' | sort -nru | head -1`
	echo ${max:-0}
}

lan_device_update_instance() {
    local iface="$1"
    local num=0
    local ssid=`$UCI_GET wireless.$iface.ssid`
    if [ -n "$ssid" ]; then
        num=`echo $iface | cut -d '[' -f2 |cut -d ']' -f1`
    fi
    echo $num
}

lan_device_add_wlan_iface() {
	local wifi_iface=`uci add wireless wifi-iface`
	uci set wireless.$wifi_iface.device="wl0"
	uci set wireless.$wifi_iface.encryption="none"
	uci set wireless.$wifi_iface.mode="ap"
	uci set wireless.$wifi_iface.ssid="DefaultSSID"
	uci commit  wireless
	/etc/init.d/network restart &> /dev/null
	echo "1"
}

lan_device_delete_wlan_iface() {
	local iface="$1"
	uci delete wireless.$iface
	uci commit wireless
	return 0
}

get_lan_device_lan_host_config_management_mac_addr()
{
    local val=`ifconfig | grep eth1 | head -1 | awk '{print$5}'`
    echo $val
}

get_lan_device_lan_host_config_management_dhcp_server_configenable()
{
    echo "1"
}

get_lan_device_lan_host_config_management_dhcp_relay()
{
    echo "1"
}

get_lan_device_lan_host_config_management_subnet_mask()
{
    local val=`uci get network.lan.netmask`
    if [ -n "$val" ]; then
        echo "$val"
    else
        echo "0.0.0.0"
    fi
}

set_lan_device_lan_host_config_management_subnet_mask()
{
    local val=$1
    uci set network.lan.netmask="$val"
    uci commit network
    return 0
}

get_lan_device_lan_host_config_management_dns_servers()
{
    local val=`uci get network.lan.dns`
    if [ -n "$val" ]; then
        echo "$val"
    else
        echo "0.0.0.0"
    fi
}

set_lan_device_lan_host_config_management_dns_servers()
{
    local val=$1
    uci set network.lan.dns="$val"
    uci commit network
    return 0
}

get_lan_device_lan_ethernet_number_of_entries()
{
    echo "10"
}

get_lan_device_wlan_number_of_entries()
{
    echo "4"
}

get_lan_device_lan_ethernet_interface_config_enable()
{
    echo "1"
}

get_lan_device_lan_ethernet_interface_config_macenabled()
{
    echo "1"
}

get_lan_device_lan_ethernet_interface_config_maxbitrate()
{
    echo "100"
}

lan_device_get_wlan_status()
{
    local iface=$1
    local disabled=$(uci get wireless.$iface.disabled) &> /dev/null
    if [ "$disabled" == "1" ]; then
    {    
        echo "Disabled"
    }
    else
        echo "UP"
    fi
}

lan_device_get_wlan_possiblechannels()
{
    echo "1-13"
}

lan_device_get_wlan_channel()
{
    local val=`uci get wireless.ra0.channel`
    if [ "$val" != "" ]; then
        echo "$val"
    else
        echo "auto"
    fi
}

lan_device_set_wlan_channel()
{
    uci set wireless.ra0.channel="$2"
    uci commit wireless
    return 0
}

lan_device_get_wlan_beacontype()
{
    local iface=$1
    local val=`uci get wireless.$iface.encryption`
    if [ "$val" == "none" ]; then
    {    
        echo "None"
    }
    elif [ "$val" == "wep-open" -o "$val" == "wep-shared" ]; then
        echo "Basic"
    else
        echo "WPA"
    fi
}

lan_device_get_wlan_Standard()
{
    local val=`uci get wireless.ra0.wifimode`
    if [ "$val" == "0" ]; then
        echo "b"
    elif [ "$val" == "1" ]; then
        echo "g"
    elif [ "$val" == "2" ]; then
        echo "b,g"
    elif [ "$val" == "3" ]; then
        echo "n"
    else
        echo "b,g,n"        
    fi
}

lan_device_set_wlan_Standard()
{
    local val=$1
    if [ "$val" == "b" ]; then
        uci set wireless.ra0.wifimode="0"
    elif [ "$val" == "g" ]; then
        uci set wireless.ra0.wifimode="1"
    elif [ "$val" == "b,g" ]; then
        uci set wireless.ra0.wifimode="2"
    elif [ "$val" == "n" ]; then
        uci set wireless.ra0.wifimode="3"
    elif [ "$val" == "b,g,n" ]; then
        uci set wireless.ra0.wifimode="4"
    else
        return $E_INVALID_PARAMETER_VALUE
    fi
    uci commit wireless
    return 0
}

lan_device_get_wlan_KeyPassphrase()
{
    local val=`uci get wireless.$1.key1`
    if [ "$val" != "" ]; then
        echo "$val"
    else
        echo "0123456789"
    fi
}

lan_device_set_wlan_KeyPassphrase()
{
    uci get wireless.$1.key1="$2"
    uci commit wireless
    return 0
}

lan_device_get_wlan_basicencrymodes()
{
    local val=`uci get wireless.$1.encryption`
    if [ "$val" != "" ]; then
        echo "$val"
    else
        echo "wep-open"
    fi
}
lan_device_set_wlan_basicencrymodes()
{
    uci get wireless.$1.encryption="$2"
    uci commit wireless
    return 0

}

lan_device_get_wlan_RadioEnabled()
{
    local val=`uci get wireless.wifi-device.radio`
    if [ "$val" != "" ]; then
        echo "$val"
    else
        echo "1"
    fi
}

lan_device_get_wlan_RadioEnabled()
{
    uci set wireless.wifi-device.radio="$2"
    uci commit wireless
    return 0
}

lan_device_get_wlan_WPAEncryptionModes()
{
    local val=`uci get wireless.$1.encryption`
    echo "$val"
}

lan_device_set_wlan_WPAEncryptionModes()
{
    uci set wireless.$1.encryption="$2"
    uci commit wireless
    return 0
}

lan_device_get_wlan_channelwh()
{
    local val=`uci get wireless.ra0.bw`
    echo "$val"
}

lan_device_set_wlan_channelwh()
{
    uci set wireless.ra0.bw="$2"
    uci commit wireless
    return 0
}

lan_device_get_wlan_powerlevel()
{
    local val=`uci get wireless.ra0.txpower`
    echo "$val"
}

lan_device_set_wlan_powerlevel()
{
    uci set wireless.ra0.txpower="$2"
    uci commit wireless
    return 0
}

lan_device_get_wlan_apenable()
{
    local val=`uci get wireless.ra0.radio`
    echo "$val"
}

lan_device_get_wlan_apenable()
{
    uci set wireless.ra0.radio="$2"
    uci commit wireless
}

lan_device_get_host_enable()
{
     local lan_if="$1"
     local val=$(uci get network.$lan_if.proto) &> /dev/null
     if [ "$val" != "" ]; then
     {    
         echo "1"
     }
     else
         echo "0"
     fi
}

lan_device_set_host_enable()
{
    return 0
}

lan_device_get_host_ip_interface()
{
     local lan_if="$1"
     local val=$(uci get network.$lan_if.ipaddr) &> /dev/null
     if [ "$val" == "" ]; then
     {    
         echo "0.0.0.0"
     }
     else
         echo "$val"
     fi
}

lan_device_set_host_ip_interface()
{
    uci set network.$lan_if.ipaddr="$2"
    uci commit network
}

lan_device_get_host_subnet_mask()
{
     local lan_if="$1"
     local val=$(uci get network.$lan_if.netmask) &> /dev/null
     if [ "$val" == "" ]; then
     {    
         echo "255.255.255.0"
     }
     else
         echo "$val"
     fi
}

lan_device_set_host_subnet_mask()
{
    uci set network.$lan_if.netmask="$2"
    uci commit network
}

lan_device_get_host_addr_type()
{
    echo "bridge"
}

