#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#############################
#   Entry point functuons   #
#############################

prefix_list="$prefix_list $DMROOT.Time."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_TIME"

entry_execute_method_root_TIME() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.Time."*)
		common_execute_method_obj "$DMROOT.Time." "0" "" "" "time_browse_instances_time_all $1"
		return 0
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

sub_entry_time_Time_All() {
	local j="$2"
	local iface="$3"
	case_param "$1" belongto "$DMROOT.Time." && {
		common_execute_method_obj "$DMROOT.Time." "0" "" ""
		common_execute_method_param "$DMROOT.Time.LocalTimeZoneName" "1" "get_InternetGatewayDevice_Time_LocalTimeZoneName" "set_InternetGatewayDevice_Time_LocalTimeZoneName" "" "1"
		common_execute_method_param "$DMROOT.Time.NTPServer1" "0" "get_InternetGatewayDevice_Time_NTPServer1" "" "" "1"
		common_execute_method_param "$DMROOT.Time.NTPServer2" "0" "get_InternetGatewayDevice_Time_NTPServer2" "" "" "1"
		return 0
	}
	return $E_INVALID_PARAMETER_NAME;
}

#######################################
#     Data model browse instances     #
#######################################

time_browse_instances_time_all(){
	sub_entry_time_Time_All "$1" "1" "1"
	return 0
}

#######################################
#   Data model parameters functions   #
#######################################

get_InternetGatewayDevice_Time_LocalTimeZoneName(){
local val=""
	val=`/sbin/uci get /etc/config/confapp.NTP.TZ`
	echo "$val"
return 0	
}
set_InternetGatewayDevice_Time_LocalTimeZoneName(){
local val=$1
local server
local cycle
	cycle=`/sbin/uci set /etc/config/confapp.NTP.cycle`
	server=`/sbin/uci set /etc/config/confapp.NTP.NTPServer`
}


get_InternetGatewayDevice_Time_NTPServer1(){
local val=""
	val=`/sbin/uci get /etc/config/confapp.NTP.NTPServer`
	echo "$val"
return 0	
}
get_InternetGatewayDevice_Time_NTPServer2(){
local val=""
	val="NULL"
	echo "$val"
return 0	
}
