#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

[ "$1" != "run" ] && return

UCI_GET_VARSTATE="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P /var/state get"
UCI_SET_VARSTATE="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P /var/state set"

download_get() {
	local val=`$UCI_GET_VARSTATE $1`
	echo ${val:-$2}
}

download_launch() {
	echo "`date`: download_launch">>/tmp/debug_download.txt
        echo "`date`: DiagnosticsState = `$UCI_GET_VARSTATE easycwmp.@local[0].DiagnosticsState`" >> /tmp/debug_download.txt
	[ "`$UCI_GET_VARSTATE easycwmp.@local[0].DiagnosticsState`" != "Requested" ] && return
	local url=`download_get easycwmp.@local[0].DownloadURL`
	local inter=`download_get easycwmp.@local[0].Interface`
	echo "`date`: url =$url ">>/tmp/debug_download.txt
	[ "$url" = "" ] && return
	echo "`date`: inter =$inter ">>/tmp/debug_download.txt
	[ "$inter" = "" ] && return
	local flag=1
	local  par
	echo "`date`: run httpdownload">>/tmp/debug_download.txt
	httpdownload $url $inter  2>&1
	while [ "$flag" != 0 ]; do	
		http_code=`cat  /tmp/httpdownload_state  | grep HTTPCode`
                echo "`date`: $http_code">>/tmp/debug_download.txt
		if [ "$http_code" = "" ]; then
			flag=1
			sleep 1
		else
			flag=0
			par=`cat /tmp/httpdownload_state  | grep ROMTime | awk -F '=' '{print $2}'`
			$UCI_SET_VARSTATE easycwmp.@local[0].ROMTime=$par
			par=`cat /tmp/httpdownload_state  | grep BOMTime | awk -F '=' '{print $2}'`
			$UCI_SET_VARSTATE easycwmp.@local[0].BOMTime=$par
			par=`cat /tmp/httpdownload_state  | grep EOMTime | awk -F '=' '{print $2}'`
			$UCI_SET_VARSTATE easycwmp.@local[0].EOMTime=$par

			par=`cat /tmp/httpdownload_state  | grep TestBytesReceived | awk -F '=' '{print $2}'`
			$UCI_SET_VARSTATE easycwmp.@local[0].TestBytesReceived=$par
			par=`cat /tmp/httpdownload_state  | grep TotalBytesReceived | awk -F '=' '{print $2}'`
			$UCI_SET_VARSTATE easycwmp.@local[0].TotalBytesReceived=$par

			par=`cat /tmp/httpdownload_state  | grep TCPOpenRequestTime | awk -F '=' '{print $2}'`
			$UCI_SET_VARSTATE easycwmp.@local[0].TCPOpenRequestTime=$par
			par=`cat /tmp/httpdownload_state  | grep TCPOpenResponseTime | awk -F '=' '{print $2}'`
			$UCI_SET_VARSTATE easycwmp.@local[0].TCPOpenResponseTime=$par
                        echo "`date`: set DiagnosticsState = Complete">>/tmp/debug_download.txt
                	$UCI_SET_VARSTATE easycwmp.@local[0].DiagnosticsState=Complete                
		fi
    done	
	
	sync
	event_dignostic
}

event_dignostic() {
	local e=1
	local i=0
	while [ "$e" != 0 -a $i -lt 200 ]; do	
		ubus -t 1 call tr069 inform '{"event":"8 DIAGNOSTICS COMPLETE"}'
		e=$?
		[ "$e" != "0" ] && sleep 1;
		let i++
	done
}

download_launch
