#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

[ "$1" != "run" ] && return

UCI_GET_VARSTATE="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P /var/state get"
UCI_SET_VARSTATE="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P /var/state set"

httpget_get() {
	local val=`$UCI_GET_VARSTATE $1`
	echo ${val:-$2}
}

httpget_launch() {
	local url=`httpget_get easycwmp.@local[0].URL`
	local repetitions=`httpget_get easycwmp.@local[0].NumberOfRepetitions`
	local timeout=`httpget_get easycwmp.@local[0].Timeout`
	
	[ "$url" = "" ] && return
	httpget $timeout $repetitions $url 
	par=`cat /tmp/httpget_state  | grep SuccessCount | awk -F '=' '{print $2}'`
	$UCI_SET_VARSTATE easycwmp.@local[0].SuccessCount=$par
	par=`cat /tmp/httpget_state  | grep FailureCount | awk -F '=' '{print $2}'`
	$UCI_SET_VARSTATE easycwmp.@local[0].FailureCount=$par
	par=`cat /tmp/httpget_state  | grep MinmumResponseTime | awk -F '=' '{print $2}'`
	$UCI_SET_VARSTATE easycwmp.@local[0].MinimumResponseTime=$par
	par=`cat /tmp/httpget_state  | grep MaximymResponseTime | awk -F '=' '{print $2}'`
	$UCI_SET_VARSTATE easycwmp.@local[0].MaximumResponseTime=$par
	par=`cat /tmp/httpget_state  | grep AverageResponseTime | awk -F '=' '{print $2}'`
	$UCI_SET_VARSTATE easycwmp.@local[0].AverageResponseTime=$par
	par=`cat /tmp/httpget_state  | grep DiagnosticState | awk -F '=' '{print $2}'`
	$UCI_SET_VARSTATE easycwmp.@local[0].DiagnosticsState=$par
	sync
	event_dignostic
}

event_dignostic() {
	local e=1
	local i=0
	while [ "$e" != 0 -a $i -lt 200 ]; do	
		ubus -t 1 call tr069 inform '{"event":"8 DIAGNOSTICS COMPLETE"}'
		e=$?
		[ "$e" != "0" ] && sleep 1;
		let i++
	done
}

httpget_launch
